version: '3'

services:
  app-go:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go
    volumes:
      - ./:/app
    ports:
      - "3000:3000"